source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'sinatra-flash'
gem 'json'
gem 'slim'
gem 'http'
gem 'econfig'
gem 'rack-flash3'

gem 'roar'
gem 'multi_json'
gem 'dry-monads'
gem 'dry-validation', '~> 0.10.4'
gem 'dry-container'
gem 'dry-transaction'
